### PR TITLE
[WIP] Fix atomic use in aqueue

### PR DESCRIPTION
**Pull request by MaxLeiter**
Credit to @Hummer12007 (need to change commit author)

Unsure if the segfaulting occuring is `aqueue`'s fault or not - seems to happened when you select emails too fast.

### CODE REVIEW

**Comment by SirCmpwn** [comment]
Is this good to go?

**Comment by Hummer12007** [comment]
I experience morr crashes with the pr. Didn't have time to look into it past few days. I propose holding it off until your refactoring merges.

**Comment by MaxLeiter** [comment]
If your refactoring is on hold @sircmpwn, can you test with this and give feedback/merge?

**Comment by SirCmpwn** [comment]
Good call.

**Comment by SirCmpwn** [comment]
Thanks!

**Comment by SirCmpwn** [comment]
FWIW it's not entirely unlikely that I'll rewrite aerc from scratch at some point in the future. Depends on whether or not I can find a language I like to replace it with.

**Pull request merged**
